import{a as v,S as q,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const E="53658397-297125985b6b4c55411510f4b",P="https://pixabay.com/api/",R=15;async function S(o,e){const i={key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:R};try{return(await v.get(P,{params:i})).data}catch(s){throw console.error("HTTP Request failed:",s),s}}const p=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector("[data-load-more]"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function $(o){const{webformatURL:e,largeImageURL:i,tags:s,likes:t,views:r,comments:n,downloads:w}=o;return`
        <li class="gallery-item">
            <a class="gallery-link" href="${i}">
                <img class="gallery-image" src="${e}" alt="${s}" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b>${t}</p>
                <p class="info-item"><b>Views</b>${r}</p>
                <p class="info-item"><b>Comments</b>${n}</p>
                <p class="info-item"><b>Downloads</b>${w}</p>
            </div>
        </li>
    `}function I(o){const e=o.map($).join("");p.insertAdjacentHTML("beforeend",e),B.refresh()}function M(){p.innerHTML=""}function g(){l&&l.classList.remove("is-hidden")}function h(){l&&l.classList.add("is-hidden")}function A(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}function G(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:2*e,behavior:"smooth"})}const y=document.querySelector(".form"),m=y.elements["search-text"],H=document.querySelector("[data-load-more]"),O=15;let b="",a=1,d=0;y.addEventListener("submit",async o=>{o.preventDefault();const e=m.value.trim();if(!e){c.warning({message:"Enter a search query.",position:"topRight"});return}b=e,a=1,M(),f(),g();try{await L()}catch{c.error({message:"Error fetching images.",position:"topRight"})}finally{h(),m.value=""}});H.addEventListener("click",async()=>{a+=1,f(),g();try{await L(!0),G()}catch{c.error({message:"Error fetching more images.",position:"topRight"})}finally{h()}});async function L(){const o=await S(b,a),e=o.hits;if(d=o.totalHits,!e.length&&a===1){c.error({message:"No images found. Try another query.",position:"topRight"});return}I(e),a*O>=d?(f(),d&&c.info({message:"You've reached the end of results.",position:"bottomCenter"})):A()}
//# sourceMappingURL=index.js.map
