import{a as q,S as E,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const P="53658397-297125985b6b4c55411510f4b",R="https://pixabay.com/api/",S=15;async function B(r,e){const s={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:S};try{return(await q.get(R,{params:s})).data}catch(i){throw console.error("HTTP Request failed:",i),i}}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector("[data-load-more]"),M=new E(".gallery a",{captionsData:"alt",captionDelay:250});function $(r){const{webformatURL:e,largeImageURL:s,tags:i,likes:t,views:o,comments:n,downloads:v}=r;return`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
                <img class="gallery-image" src="${e}" alt="${i}" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b>${t}</p>
                <p class="info-item"><b>Views</b>${o}</p>
                <p class="info-item"><b>Comments</b>${n}</p>
                <p class="info-item"><b>Downloads</b>${v}</p>
            </div>
        </li>
    `}function I(r){const e=r.map($).join("");h.insertAdjacentHTML("beforeend",e),M.refresh()}function A(){h.innerHTML=""}function g(){l&&l.classList.remove("is-hidden")}function y(){l&&l.classList.add("is-hidden")}function G(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}function H(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:2*e,behavior:"smooth"})}const L=document.querySelector(".form"),m=L.elements["search-text"],O=document.querySelector("[data-load-more]"),p=15;let b="",a=1,u=0;L.addEventListener("submit",async r=>{r.preventDefault();const e=m.value.trim();if(!e){c.warning({message:"Enter a search query.",position:"topRight"});return}b=e,a=1,A(),f(),g();try{await w()}catch{c.error({message:"Error fetching images.",position:"topRight"})}finally{y(),m.value=""}});O.addEventListener("click",async()=>{a+=1,f(),g();try{await w(!0),H()}catch{c.error({message:"Error fetching more images.",position:"topRight"})}finally{y()}});async function w(r=!1){try{const e=await B(b,a,p),s=e.hits;if(u=e.totalHits,!s.length&&a===1){c.error({message:"No images found. Try another query.",position:"topRight"});return}I(s),(a-1)*p+s.length>=u?(f(),u&&c.info({message:"We've reached the end of results.",position:"bottomCenter"})):G()}catch(e){throw e}}
//# sourceMappingURL=index.js.map
